# Generated by Django 5.1 on 2025-12-26 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_time', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('status', models.CharField(choices=[('registered', '已报名'), ('cancelled', '已取消'), ('attended', '已参加')], default='registered', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='activities.activity', verbose_name='活动')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '报名记录',
                'verbose_name_plural': '报名记录',
                'db_table': 'enrollment',
                'unique_together': {('user', 'activity')},
            },
        ),
    ]
