# Generated by Django 5.1 on 2025-12-26 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='学号')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话')),
                ('role', models.CharField(choices=[('student', '学生'), ('organizer', '活动组织者'), ('admin', '系统管理员')], default='student', max_length=20, verbose_name='角色')),
                ('college', models.CharField(blank=True, max_length=100, null=True, verbose_name='学院')),
                ('major', models.CharField(blank=True, max_length=100, null=True, verbose_name='专业')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户扩展信息',
                'verbose_name_plural': '用户扩展信息',
                'db_table': 'user_profile',
            },
        ),
    ]
