# Generated by Django 6.0 on 2025-12-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('academic', '学术讲座'), ('cultural', '文艺表演'), ('sports', '体育竞赛'), ('volunteer', '志愿服务'), ('competition', '创新大赛'), ('other', '其他')], default='other', max_length=20, verbose_name='活动类别'),
        ),
    ]
