# Generated by Django 5.1 on 2025-12-26 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.DateTimeField(auto_now_add=True, verbose_name='签到时间')),
                ('checkin_method', models.CharField(choices=[('qr_code', '二维码'), ('manual', '手动')], default='qr_code', max_length=20, verbose_name='签到方式')),
                ('device_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='设备信息')),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='IP地址')),
                ('qr_token', models.CharField(blank=True, max_length=100, null=True, verbose_name='二维码令牌')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='enrollments.enrollment', verbose_name='报名记录')),
            ],
            options={
                'verbose_name': '签到记录',
                'verbose_name_plural': '签到记录',
                'db_table': 'attendance',
            },
        ),
    ]
