# Generated by Django 6.0 on 2026-05-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='设备标识'),
        ),
    ]
